name: docker-release.yml
on:
  push:
    tags:
      - 'v*'  # Тригериться при пуші тегів, як-от v1.0.0

permissions:
  contents: write

jobs:
  docker-release:
    runs-on: ubuntu-latest

    steps:
      - name: Клонувати репозиторій
        uses: actions/checkout@v4

      - name: Налаштувати Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Зібрати Docker-образ
        run: |
          docker build -t pigeon-auth_service:${{ github.ref_name }} .  && \
          docker tag pigeon-auth_service:${{ github.ref_name }} pigeon-auth_service:latest


      - name: Зберегти Docker-образ у файл
        run: |
            docker save pigeon-auth_service:${{ github.ref_name }} -o pigeon-auth_service-${{ github.ref_name }}.tar && \
            docker save pigeon-auth_service:latest -o pigeon-auth_service-latest.tar

      - name: Завантажити файл у GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: pigeon-auth_service-${{ github.ref_name }}.tar
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Завантажити файл latest у GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release latest
          tag_name: latest
          files: pigeon-auth_service-latest.tar
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
